/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the AddAPITokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAPITokenRequest{}

// AddAPITokenRequest struct for AddAPITokenRequest
type AddAPITokenRequest struct {
	Resource *string `json:"resource,omitempty"`
	Name *string `json:"name,omitempty"`
	Write *bool `json:"write,omitempty"`
}

// NewAddAPITokenRequest instantiates a new AddAPITokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAPITokenRequest() *AddAPITokenRequest {
	this := AddAPITokenRequest{}
	return &this
}

// NewAddAPITokenRequestWithDefaults instantiates a new AddAPITokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAPITokenRequestWithDefaults() *AddAPITokenRequest {
	this := AddAPITokenRequest{}
	return &this
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *AddAPITokenRequest) GetResource() string {
	if o == nil || IsNil(o.Resource) {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAPITokenRequest) GetResourceOk() (*string, bool) {
	if o == nil || IsNil(o.Resource) {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *AddAPITokenRequest) HasResource() bool {
	if o != nil && !IsNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *AddAPITokenRequest) SetResource(v string) {
	o.Resource = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AddAPITokenRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAPITokenRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AddAPITokenRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AddAPITokenRequest) SetName(v string) {
	o.Name = &v
}

// GetWrite returns the Write field value if set, zero value otherwise.
func (o *AddAPITokenRequest) GetWrite() bool {
	if o == nil || IsNil(o.Write) {
		var ret bool
		return ret
	}
	return *o.Write
}

// GetWriteOk returns a tuple with the Write field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAPITokenRequest) GetWriteOk() (*bool, bool) {
	if o == nil || IsNil(o.Write) {
		return nil, false
	}
	return o.Write, true
}

// HasWrite returns a boolean if a field has been set.
func (o *AddAPITokenRequest) HasWrite() bool {
	if o != nil && !IsNil(o.Write) {
		return true
	}

	return false
}

// SetWrite gets a reference to the given bool and assigns it to the Write field.
func (o *AddAPITokenRequest) SetWrite(v bool) {
	o.Write = &v
}

func (o AddAPITokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAPITokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Write) {
		toSerialize["write"] = o.Write
	}
	return toSerialize, nil
}

type NullableAddAPITokenRequest struct {
	value *AddAPITokenRequest
	isSet bool
}

func (v NullableAddAPITokenRequest) Get() *AddAPITokenRequest {
	return v.value
}

func (v *NullableAddAPITokenRequest) Set(val *AddAPITokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAPITokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAPITokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAPITokenRequest(val *AddAPITokenRequest) *NullableAddAPITokenRequest {
	return &NullableAddAPITokenRequest{value: val, isSet: true}
}

func (v NullableAddAPITokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAPITokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


