/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the CreateOrgInvitesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrgInvitesResponse{}

// CreateOrgInvitesResponse struct for CreateOrgInvitesResponse
type CreateOrgInvitesResponse struct {
	Invites *int32 `json:"invites,omitempty"`
}

// NewCreateOrgInvitesResponse instantiates a new CreateOrgInvitesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrgInvitesResponse() *CreateOrgInvitesResponse {
	this := CreateOrgInvitesResponse{}
	return &this
}

// NewCreateOrgInvitesResponseWithDefaults instantiates a new CreateOrgInvitesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrgInvitesResponseWithDefaults() *CreateOrgInvitesResponse {
	this := CreateOrgInvitesResponse{}
	return &this
}

// GetInvites returns the Invites field value if set, zero value otherwise.
func (o *CreateOrgInvitesResponse) GetInvites() int32 {
	if o == nil || IsNil(o.Invites) {
		var ret int32
		return ret
	}
	return *o.Invites
}

// GetInvitesOk returns a tuple with the Invites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrgInvitesResponse) GetInvitesOk() (*int32, bool) {
	if o == nil || IsNil(o.Invites) {
		return nil, false
	}
	return o.Invites, true
}

// HasInvites returns a boolean if a field has been set.
func (o *CreateOrgInvitesResponse) HasInvites() bool {
	if o != nil && !IsNil(o.Invites) {
		return true
	}

	return false
}

// SetInvites gets a reference to the given int32 and assigns it to the Invites field.
func (o *CreateOrgInvitesResponse) SetInvites(v int32) {
	o.Invites = &v
}

func (o CreateOrgInvitesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrgInvitesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Invites) {
		toSerialize["invites"] = o.Invites
	}
	return toSerialize, nil
}

type NullableCreateOrgInvitesResponse struct {
	value *CreateOrgInvitesResponse
	isSet bool
}

func (v NullableCreateOrgInvitesResponse) Get() *CreateOrgInvitesResponse {
	return v.value
}

func (v *NullableCreateOrgInvitesResponse) Set(val *CreateOrgInvitesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrgInvitesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrgInvitesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrgInvitesResponse(val *CreateOrgInvitesResponse) *NullableCreateOrgInvitesResponse {
	return &NullableCreateOrgInvitesResponse{value: val, isSet: true}
}

func (v NullableCreateOrgInvitesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrgInvitesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


