/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the GetSigningKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSigningKeyResponse{}

// GetSigningKeyResponse struct for GetSigningKeyResponse
type GetSigningKeyResponse struct {
	PublicKey *string `json:"publicKey,omitempty"`
}

// NewGetSigningKeyResponse instantiates a new GetSigningKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSigningKeyResponse() *GetSigningKeyResponse {
	this := GetSigningKeyResponse{}
	return &this
}

// NewGetSigningKeyResponseWithDefaults instantiates a new GetSigningKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSigningKeyResponseWithDefaults() *GetSigningKeyResponse {
	this := GetSigningKeyResponse{}
	return &this
}

// GetPublicKey returns the PublicKey field value if set, zero value otherwise.
func (o *GetSigningKeyResponse) GetPublicKey() string {
	if o == nil || IsNil(o.PublicKey) {
		var ret string
		return ret
	}
	return *o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSigningKeyResponse) GetPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PublicKey) {
		return nil, false
	}
	return o.PublicKey, true
}

// HasPublicKey returns a boolean if a field has been set.
func (o *GetSigningKeyResponse) HasPublicKey() bool {
	if o != nil && !IsNil(o.PublicKey) {
		return true
	}

	return false
}

// SetPublicKey gets a reference to the given string and assigns it to the PublicKey field.
func (o *GetSigningKeyResponse) SetPublicKey(v string) {
	o.PublicKey = &v
}

func (o GetSigningKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSigningKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PublicKey) {
		toSerialize["publicKey"] = o.PublicKey
	}
	return toSerialize, nil
}

type NullableGetSigningKeyResponse struct {
	value *GetSigningKeyResponse
	isSet bool
}

func (v NullableGetSigningKeyResponse) Get() *GetSigningKeyResponse {
	return v.value
}

func (v *NullableGetSigningKeyResponse) Set(val *GetSigningKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSigningKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSigningKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSigningKeyResponse(val *GetSigningKeyResponse) *NullableGetSigningKeyResponse {
	return &NullableGetSigningKeyResponse{value: val, isSet: true}
}

func (v NullableGetSigningKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSigningKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


