/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the VerifyEmailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyEmailRequest{}

// VerifyEmailRequest struct for VerifyEmailRequest
type VerifyEmailRequest struct {
	Token *string `json:"token,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewVerifyEmailRequest instantiates a new VerifyEmailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyEmailRequest() *VerifyEmailRequest {
	this := VerifyEmailRequest{}
	return &this
}

// NewVerifyEmailRequestWithDefaults instantiates a new VerifyEmailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyEmailRequestWithDefaults() *VerifyEmailRequest {
	this := VerifyEmailRequest{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *VerifyEmailRequest) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyEmailRequest) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *VerifyEmailRequest) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *VerifyEmailRequest) SetToken(v string) {
	o.Token = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *VerifyEmailRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyEmailRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *VerifyEmailRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *VerifyEmailRequest) SetPassword(v string) {
	o.Password = &v
}

func (o VerifyEmailRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyEmailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableVerifyEmailRequest struct {
	value *VerifyEmailRequest
	isSet bool
}

func (v NullableVerifyEmailRequest) Get() *VerifyEmailRequest {
	return v.value
}

func (v *NullableVerifyEmailRequest) Set(val *VerifyEmailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyEmailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyEmailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyEmailRequest(val *VerifyEmailRequest) *NullableVerifyEmailRequest {
	return &NullableVerifyEmailRequest{value: val, isSet: true}
}

func (v NullableVerifyEmailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyEmailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


