/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the SignupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignupResponse{}

// SignupResponse struct for SignupResponse
type SignupResponse struct {
	Result *SignupResponseResult `json:"result,omitempty"`
}

// NewSignupResponse instantiates a new SignupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignupResponse() *SignupResponse {
	this := SignupResponse{}
	var result SignupResponseResult = SIGNUPRESPONSERESULT_UNSPECIFIED
	this.Result = &result
	return &this
}

// NewSignupResponseWithDefaults instantiates a new SignupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignupResponseWithDefaults() *SignupResponse {
	this := SignupResponse{}
	var result SignupResponseResult = SIGNUPRESPONSERESULT_UNSPECIFIED
	this.Result = &result
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *SignupResponse) GetResult() SignupResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret SignupResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignupResponse) GetResultOk() (*SignupResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *SignupResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given SignupResponseResult and assigns it to the Result field.
func (o *SignupResponse) SetResult(v SignupResponseResult) {
	o.Result = &v
}

func (o SignupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableSignupResponse struct {
	value *SignupResponse
	isSet bool
}

func (v NullableSignupResponse) Get() *SignupResponse {
	return v.value
}

func (v *NullableSignupResponse) Set(val *SignupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSignupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSignupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignupResponse(val *SignupResponse) *NullableSignupResponse {
	return &NullableSignupResponse{value: val, isSet: true}
}

func (v NullableSignupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


