/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the UpdateOrgTeamRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrgTeamRequest{}

// UpdateOrgTeamRequest struct for UpdateOrgTeamRequest
type UpdateOrgTeamRequest struct {
	Name *string `json:"name,omitempty"`
	NewOrgId *string `json:"newOrgId,omitempty"`
}

// NewUpdateOrgTeamRequest instantiates a new UpdateOrgTeamRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrgTeamRequest() *UpdateOrgTeamRequest {
	this := UpdateOrgTeamRequest{}
	return &this
}

// NewUpdateOrgTeamRequestWithDefaults instantiates a new UpdateOrgTeamRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrgTeamRequestWithDefaults() *UpdateOrgTeamRequest {
	this := UpdateOrgTeamRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateOrgTeamRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrgTeamRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateOrgTeamRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateOrgTeamRequest) SetName(v string) {
	o.Name = &v
}

// GetNewOrgId returns the NewOrgId field value if set, zero value otherwise.
func (o *UpdateOrgTeamRequest) GetNewOrgId() string {
	if o == nil || IsNil(o.NewOrgId) {
		var ret string
		return ret
	}
	return *o.NewOrgId
}

// GetNewOrgIdOk returns a tuple with the NewOrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrgTeamRequest) GetNewOrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.NewOrgId) {
		return nil, false
	}
	return o.NewOrgId, true
}

// HasNewOrgId returns a boolean if a field has been set.
func (o *UpdateOrgTeamRequest) HasNewOrgId() bool {
	if o != nil && !IsNil(o.NewOrgId) {
		return true
	}

	return false
}

// SetNewOrgId gets a reference to the given string and assigns it to the NewOrgId field.
func (o *UpdateOrgTeamRequest) SetNewOrgId(v string) {
	o.NewOrgId = &v
}

func (o UpdateOrgTeamRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrgTeamRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NewOrgId) {
		toSerialize["newOrgId"] = o.NewOrgId
	}
	return toSerialize, nil
}

type NullableUpdateOrgTeamRequest struct {
	value *UpdateOrgTeamRequest
	isSet bool
}

func (v NullableUpdateOrgTeamRequest) Get() *UpdateOrgTeamRequest {
	return v.value
}

func (v *NullableUpdateOrgTeamRequest) Set(val *UpdateOrgTeamRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrgTeamRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrgTeamRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrgTeamRequest(val *UpdateOrgTeamRequest) *NullableUpdateOrgTeamRequest {
	return &NullableUpdateOrgTeamRequest{value: val, isSet: true}
}

func (v NullableUpdateOrgTeamRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrgTeamRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


