/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the UpdateAPITokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAPITokenRequest{}

// UpdateAPITokenRequest struct for UpdateAPITokenRequest
type UpdateAPITokenRequest struct {
	Resource *string `json:"resource,omitempty"`
	Write *bool `json:"write,omitempty"`
	Name *string `json:"name,omitempty"`
	NewTeamId *string `json:"newTeamId,omitempty"`
}

// NewUpdateAPITokenRequest instantiates a new UpdateAPITokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAPITokenRequest() *UpdateAPITokenRequest {
	this := UpdateAPITokenRequest{}
	return &this
}

// NewUpdateAPITokenRequestWithDefaults instantiates a new UpdateAPITokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAPITokenRequestWithDefaults() *UpdateAPITokenRequest {
	this := UpdateAPITokenRequest{}
	return &this
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *UpdateAPITokenRequest) GetResource() string {
	if o == nil || IsNil(o.Resource) {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAPITokenRequest) GetResourceOk() (*string, bool) {
	if o == nil || IsNil(o.Resource) {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *UpdateAPITokenRequest) HasResource() bool {
	if o != nil && !IsNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *UpdateAPITokenRequest) SetResource(v string) {
	o.Resource = &v
}

// GetWrite returns the Write field value if set, zero value otherwise.
func (o *UpdateAPITokenRequest) GetWrite() bool {
	if o == nil || IsNil(o.Write) {
		var ret bool
		return ret
	}
	return *o.Write
}

// GetWriteOk returns a tuple with the Write field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAPITokenRequest) GetWriteOk() (*bool, bool) {
	if o == nil || IsNil(o.Write) {
		return nil, false
	}
	return o.Write, true
}

// HasWrite returns a boolean if a field has been set.
func (o *UpdateAPITokenRequest) HasWrite() bool {
	if o != nil && !IsNil(o.Write) {
		return true
	}

	return false
}

// SetWrite gets a reference to the given bool and assigns it to the Write field.
func (o *UpdateAPITokenRequest) SetWrite(v bool) {
	o.Write = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateAPITokenRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAPITokenRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateAPITokenRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateAPITokenRequest) SetName(v string) {
	o.Name = &v
}

// GetNewTeamId returns the NewTeamId field value if set, zero value otherwise.
func (o *UpdateAPITokenRequest) GetNewTeamId() string {
	if o == nil || IsNil(o.NewTeamId) {
		var ret string
		return ret
	}
	return *o.NewTeamId
}

// GetNewTeamIdOk returns a tuple with the NewTeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAPITokenRequest) GetNewTeamIdOk() (*string, bool) {
	if o == nil || IsNil(o.NewTeamId) {
		return nil, false
	}
	return o.NewTeamId, true
}

// HasNewTeamId returns a boolean if a field has been set.
func (o *UpdateAPITokenRequest) HasNewTeamId() bool {
	if o != nil && !IsNil(o.NewTeamId) {
		return true
	}

	return false
}

// SetNewTeamId gets a reference to the given string and assigns it to the NewTeamId field.
func (o *UpdateAPITokenRequest) SetNewTeamId(v string) {
	o.NewTeamId = &v
}

func (o UpdateAPITokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAPITokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	if !IsNil(o.Write) {
		toSerialize["write"] = o.Write
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NewTeamId) {
		toSerialize["newTeamId"] = o.NewTeamId
	}
	return toSerialize, nil
}

type NullableUpdateAPITokenRequest struct {
	value *UpdateAPITokenRequest
	isSet bool
}

func (v NullableUpdateAPITokenRequest) Get() *UpdateAPITokenRequest {
	return v.value
}

func (v *NullableUpdateAPITokenRequest) Set(val *UpdateAPITokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAPITokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAPITokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAPITokenRequest(val *UpdateAPITokenRequest) *NullableUpdateAPITokenRequest {
	return &NullableUpdateAPITokenRequest{value: val, isSet: true}
}

func (v NullableUpdateAPITokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAPITokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


