/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the ListOrgMembersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOrgMembersResponse{}

// ListOrgMembersResponse struct for ListOrgMembersResponse
type ListOrgMembersResponse struct {
	Members []OrgMember `json:"members,omitempty"`
}

// NewListOrgMembersResponse instantiates a new ListOrgMembersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOrgMembersResponse() *ListOrgMembersResponse {
	this := ListOrgMembersResponse{}
	return &this
}

// NewListOrgMembersResponseWithDefaults instantiates a new ListOrgMembersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOrgMembersResponseWithDefaults() *ListOrgMembersResponse {
	this := ListOrgMembersResponse{}
	return &this
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *ListOrgMembersResponse) GetMembers() []OrgMember {
	if o == nil || IsNil(o.Members) {
		var ret []OrgMember
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOrgMembersResponse) GetMembersOk() ([]OrgMember, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *ListOrgMembersResponse) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []OrgMember and assigns it to the Members field.
func (o *ListOrgMembersResponse) SetMembers(v []OrgMember) {
	o.Members = v
}

func (o ListOrgMembersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOrgMembersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	return toSerialize, nil
}

type NullableListOrgMembersResponse struct {
	value *ListOrgMembersResponse
	isSet bool
}

func (v NullableListOrgMembersResponse) Get() *ListOrgMembersResponse {
	return v.value
}

func (v *NullableListOrgMembersResponse) Set(val *ListOrgMembersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListOrgMembersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListOrgMembersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOrgMembersResponse(val *ListOrgMembersResponse) *NullableListOrgMembersResponse {
	return &NullableListOrgMembersResponse{value: val, isSet: true}
}

func (v NullableListOrgMembersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOrgMembersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


