/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the RecoverPasswordResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecoverPasswordResponse{}

// RecoverPasswordResponse struct for RecoverPasswordResponse
type RecoverPasswordResponse struct {
	Credentials *string `json:"credentials,omitempty"`
}

// NewRecoverPasswordResponse instantiates a new RecoverPasswordResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecoverPasswordResponse() *RecoverPasswordResponse {
	this := RecoverPasswordResponse{}
	return &this
}

// NewRecoverPasswordResponseWithDefaults instantiates a new RecoverPasswordResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecoverPasswordResponseWithDefaults() *RecoverPasswordResponse {
	this := RecoverPasswordResponse{}
	return &this
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *RecoverPasswordResponse) GetCredentials() string {
	if o == nil || IsNil(o.Credentials) {
		var ret string
		return ret
	}
	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecoverPasswordResponse) GetCredentialsOk() (*string, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *RecoverPasswordResponse) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given string and assigns it to the Credentials field.
func (o *RecoverPasswordResponse) SetCredentials(v string) {
	o.Credentials = &v
}

func (o RecoverPasswordResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecoverPasswordResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}
	return toSerialize, nil
}

type NullableRecoverPasswordResponse struct {
	value *RecoverPasswordResponse
	isSet bool
}

func (v NullableRecoverPasswordResponse) Get() *RecoverPasswordResponse {
	return v.value
}

func (v *NullableRecoverPasswordResponse) Set(val *RecoverPasswordResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoverPasswordResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoverPasswordResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoverPasswordResponse(val *RecoverPasswordResponse) *NullableRecoverPasswordResponse {
	return &NullableRecoverPasswordResponse{value: val, isSet: true}
}

func (v NullableRecoverPasswordResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoverPasswordResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


