/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the UpdatePasswordResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePasswordResponse{}

// UpdatePasswordResponse struct for UpdatePasswordResponse
type UpdatePasswordResponse struct {
	User *User `json:"user,omitempty"`
}

// NewUpdatePasswordResponse instantiates a new UpdatePasswordResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePasswordResponse() *UpdatePasswordResponse {
	this := UpdatePasswordResponse{}
	return &this
}

// NewUpdatePasswordResponseWithDefaults instantiates a new UpdatePasswordResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePasswordResponseWithDefaults() *UpdatePasswordResponse {
	this := UpdatePasswordResponse{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *UpdatePasswordResponse) GetUser() User {
	if o == nil || IsNil(o.User) {
		var ret User
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePasswordResponse) GetUserOk() (*User, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *UpdatePasswordResponse) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given User and assigns it to the User field.
func (o *UpdatePasswordResponse) SetUser(v User) {
	o.User = &v
}

func (o UpdatePasswordResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePasswordResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableUpdatePasswordResponse struct {
	value *UpdatePasswordResponse
	isSet bool
}

func (v NullableUpdatePasswordResponse) Get() *UpdatePasswordResponse {
	return v.value
}

func (v *NullableUpdatePasswordResponse) Set(val *UpdatePasswordResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePasswordResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePasswordResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePasswordResponse(val *UpdatePasswordResponse) *NullableUpdatePasswordResponse {
	return &NullableUpdatePasswordResponse{value: val, isSet: true}
}

func (v NullableUpdatePasswordResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePasswordResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


