/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the VerifyGithubProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyGithubProfileRequest{}

// VerifyGithubProfileRequest Request sent from the client when the verification link is received
type VerifyGithubProfileRequest struct {
	Password *string `json:"password,omitempty"`
}

// NewVerifyGithubProfileRequest instantiates a new VerifyGithubProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyGithubProfileRequest() *VerifyGithubProfileRequest {
	this := VerifyGithubProfileRequest{}
	return &this
}

// NewVerifyGithubProfileRequestWithDefaults instantiates a new VerifyGithubProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyGithubProfileRequestWithDefaults() *VerifyGithubProfileRequest {
	this := VerifyGithubProfileRequest{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *VerifyGithubProfileRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyGithubProfileRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *VerifyGithubProfileRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *VerifyGithubProfileRequest) SetPassword(v string) {
	o.Password = &v
}

func (o VerifyGithubProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyGithubProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableVerifyGithubProfileRequest struct {
	value *VerifyGithubProfileRequest
	isSet bool
}

func (v NullableVerifyGithubProfileRequest) Get() *VerifyGithubProfileRequest {
	return v.value
}

func (v *NullableVerifyGithubProfileRequest) Set(val *VerifyGithubProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyGithubProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyGithubProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyGithubProfileRequest(val *VerifyGithubProfileRequest) *NullableVerifyGithubProfileRequest {
	return &NullableVerifyGithubProfileRequest{value: val, isSet: true}
}

func (v NullableVerifyGithubProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyGithubProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


