/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the RemoveMFATokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveMFATokenRequest{}

// RemoveMFATokenRequest struct for RemoveMFATokenRequest
type RemoveMFATokenRequest struct {
	Passcode *string `json:"passcode,omitempty"`
}

// NewRemoveMFATokenRequest instantiates a new RemoveMFATokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveMFATokenRequest() *RemoveMFATokenRequest {
	this := RemoveMFATokenRequest{}
	return &this
}

// NewRemoveMFATokenRequestWithDefaults instantiates a new RemoveMFATokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveMFATokenRequestWithDefaults() *RemoveMFATokenRequest {
	this := RemoveMFATokenRequest{}
	return &this
}

// GetPasscode returns the Passcode field value if set, zero value otherwise.
func (o *RemoveMFATokenRequest) GetPasscode() string {
	if o == nil || IsNil(o.Passcode) {
		var ret string
		return ret
	}
	return *o.Passcode
}

// GetPasscodeOk returns a tuple with the Passcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveMFATokenRequest) GetPasscodeOk() (*string, bool) {
	if o == nil || IsNil(o.Passcode) {
		return nil, false
	}
	return o.Passcode, true
}

// HasPasscode returns a boolean if a field has been set.
func (o *RemoveMFATokenRequest) HasPasscode() bool {
	if o != nil && !IsNil(o.Passcode) {
		return true
	}

	return false
}

// SetPasscode gets a reference to the given string and assigns it to the Passcode field.
func (o *RemoveMFATokenRequest) SetPasscode(v string) {
	o.Passcode = &v
}

func (o RemoveMFATokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveMFATokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Passcode) {
		toSerialize["passcode"] = o.Passcode
	}
	return toSerialize, nil
}

type NullableRemoveMFATokenRequest struct {
	value *RemoveMFATokenRequest
	isSet bool
}

func (v NullableRemoveMFATokenRequest) Get() *RemoveMFATokenRequest {
	return v.value
}

func (v *NullableRemoveMFATokenRequest) Set(val *RemoveMFATokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveMFATokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveMFATokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveMFATokenRequest(val *RemoveMFATokenRequest) *NullableRemoveMFATokenRequest {
	return &NullableRemoveMFATokenRequest{value: val, isSet: true}
}

func (v NullableRemoveMFATokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveMFATokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


