/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the VerifyGithubProfileResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyGithubProfileResponse{}

// VerifyGithubProfileResponse Response from server. The auth token is an authentication token
type VerifyGithubProfileResponse struct {
	Credentials *string `json:"credentials,omitempty"`
}

// NewVerifyGithubProfileResponse instantiates a new VerifyGithubProfileResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyGithubProfileResponse() *VerifyGithubProfileResponse {
	this := VerifyGithubProfileResponse{}
	return &this
}

// NewVerifyGithubProfileResponseWithDefaults instantiates a new VerifyGithubProfileResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyGithubProfileResponseWithDefaults() *VerifyGithubProfileResponse {
	this := VerifyGithubProfileResponse{}
	return &this
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *VerifyGithubProfileResponse) GetCredentials() string {
	if o == nil || IsNil(o.Credentials) {
		var ret string
		return ret
	}
	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyGithubProfileResponse) GetCredentialsOk() (*string, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *VerifyGithubProfileResponse) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given string and assigns it to the Credentials field.
func (o *VerifyGithubProfileResponse) SetCredentials(v string) {
	o.Credentials = &v
}

func (o VerifyGithubProfileResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyGithubProfileResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}
	return toSerialize, nil
}

type NullableVerifyGithubProfileResponse struct {
	value *VerifyGithubProfileResponse
	isSet bool
}

func (v NullableVerifyGithubProfileResponse) Get() *VerifyGithubProfileResponse {
	return v.value
}

func (v *NullableVerifyGithubProfileResponse) Set(val *VerifyGithubProfileResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyGithubProfileResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyGithubProfileResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyGithubProfileResponse(val *VerifyGithubProfileResponse) *NullableVerifyGithubProfileResponse {
	return &NullableVerifyGithubProfileResponse{value: val, isSet: true}
}

func (v NullableVerifyGithubProfileResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyGithubProfileResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


