/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the VerifyNewMFATokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyNewMFATokenResponse{}

// VerifyNewMFATokenResponse struct for VerifyNewMFATokenResponse
type VerifyNewMFATokenResponse struct {
	User *User `json:"user,omitempty"`
}

// NewVerifyNewMFATokenResponse instantiates a new VerifyNewMFATokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyNewMFATokenResponse() *VerifyNewMFATokenResponse {
	this := VerifyNewMFATokenResponse{}
	return &this
}

// NewVerifyNewMFATokenResponseWithDefaults instantiates a new VerifyNewMFATokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyNewMFATokenResponseWithDefaults() *VerifyNewMFATokenResponse {
	this := VerifyNewMFATokenResponse{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *VerifyNewMFATokenResponse) GetUser() User {
	if o == nil || IsNil(o.User) {
		var ret User
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyNewMFATokenResponse) GetUserOk() (*User, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *VerifyNewMFATokenResponse) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given User and assigns it to the User field.
func (o *VerifyNewMFATokenResponse) SetUser(v User) {
	o.User = &v
}

func (o VerifyNewMFATokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyNewMFATokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableVerifyNewMFATokenResponse struct {
	value *VerifyNewMFATokenResponse
	isSet bool
}

func (v NullableVerifyNewMFATokenResponse) Get() *VerifyNewMFATokenResponse {
	return v.value
}

func (v *NullableVerifyNewMFATokenResponse) Set(val *VerifyNewMFATokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyNewMFATokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyNewMFATokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyNewMFATokenResponse(val *VerifyNewMFATokenResponse) *NullableVerifyNewMFATokenResponse {
	return &NullableVerifyNewMFATokenResponse{value: val, isSet: true}
}

func (v NullableVerifyNewMFATokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyNewMFATokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


