/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the VerifyEmailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyEmailResponse{}

// VerifyEmailResponse The response to verified emails concludes the signup process and credentials for a new session is returned.
type VerifyEmailResponse struct {
	Result *VerifyEmailResponseResult `json:"result,omitempty"`
	Credentials *string `json:"credentials,omitempty"`
}

// NewVerifyEmailResponse instantiates a new VerifyEmailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyEmailResponse() *VerifyEmailResponse {
	this := VerifyEmailResponse{}
	var result VerifyEmailResponseResult = VERIFYEMAILRESPONSERESULT_UNSPECIFIED
	this.Result = &result
	return &this
}

// NewVerifyEmailResponseWithDefaults instantiates a new VerifyEmailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyEmailResponseWithDefaults() *VerifyEmailResponse {
	this := VerifyEmailResponse{}
	var result VerifyEmailResponseResult = VERIFYEMAILRESPONSERESULT_UNSPECIFIED
	this.Result = &result
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *VerifyEmailResponse) GetResult() VerifyEmailResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret VerifyEmailResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyEmailResponse) GetResultOk() (*VerifyEmailResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *VerifyEmailResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given VerifyEmailResponseResult and assigns it to the Result field.
func (o *VerifyEmailResponse) SetResult(v VerifyEmailResponseResult) {
	o.Result = &v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *VerifyEmailResponse) GetCredentials() string {
	if o == nil || IsNil(o.Credentials) {
		var ret string
		return ret
	}
	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyEmailResponse) GetCredentialsOk() (*string, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *VerifyEmailResponse) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given string and assigns it to the Credentials field.
func (o *VerifyEmailResponse) SetCredentials(v string) {
	o.Credentials = &v
}

func (o VerifyEmailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyEmailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}
	return toSerialize, nil
}

type NullableVerifyEmailResponse struct {
	value *VerifyEmailResponse
	isSet bool
}

func (v NullableVerifyEmailResponse) Get() *VerifyEmailResponse {
	return v.value
}

func (v *NullableVerifyEmailResponse) Set(val *VerifyEmailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyEmailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyEmailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyEmailResponse(val *VerifyEmailResponse) *NullableVerifyEmailResponse {
	return &NullableVerifyEmailResponse{value: val, isSet: true}
}

func (v NullableVerifyEmailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyEmailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


