/*
The Span User API

API for sessions, teams and API tokens

API version: [version] [name]
Contact: contact@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanuserapi

import (
	"encoding/json"
)

// checks if the CreateOrgRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrgRequest{}

// CreateOrgRequest struct for CreateOrgRequest
type CreateOrgRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewCreateOrgRequest instantiates a new CreateOrgRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrgRequest() *CreateOrgRequest {
	this := CreateOrgRequest{}
	return &this
}

// NewCreateOrgRequestWithDefaults instantiates a new CreateOrgRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrgRequestWithDefaults() *CreateOrgRequest {
	this := CreateOrgRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateOrgRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrgRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateOrgRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateOrgRequest) SetName(v string) {
	o.Name = &v
}

func (o CreateOrgRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrgRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCreateOrgRequest struct {
	value *CreateOrgRequest
	isSet bool
}

func (v NullableCreateOrgRequest) Get() *CreateOrgRequest {
	return v.value
}

func (v *NullableCreateOrgRequest) Set(val *CreateOrgRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrgRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrgRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrgRequest(val *CreateOrgRequest) *NullableCreateOrgRequest {
	return &NullableCreateOrgRequest{value: val, isSet: true}
}

func (v NullableCreateOrgRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrgRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


